let User,CustomErrorHandler,aboutSchema;_50b‍.x([["default",()=>_50b‍.o]]);_50b‍.w("../../models",[["User",["User"],function(v){User=v}]]);_50b‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);_50b‍.w("../../validators/about",[["default",["aboutSchema"],function(v){aboutSchema=v}]]);



const userController = {
    async me(req, res, next) {
        try {
            const user = await User.findOne({ _id: req.user._id }).select('-password -updatedAt -__v');
            if (!user) {
                return res.status(400).json({
                    status: false,
                    massage:"404 Not Found"
                });
            }
            res.status(200).json({
                status:true,
               data: user,
               massage:"successfully"
            })
        } catch(err) {
           return next(err);
        }
    },
    async about(req,res,next){
        res.status(200).json({
            status:true,
           data: aboutSchema,
           massage:"successfully"
        })
    }
};

_50b‍.d(userController);